carpool/carpool/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url('', include('social.apps.django_app.urls', namespace='social')),
	url(r'^routes/', include('routes.urls', namespace="routes")),
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),
    url(r'^admin/', include(admin.site.urls)),
]

carpool/routes/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^postride/', views.postride, name='postride'),
    url(r'^getride/', views.getride, name='getride'),
    url(r'^createride/', views.createride.as_view(), name='createride'),
    url(r'^retrieveride/(?P<page_id>[0-9]+)/', views.retrieveride, name='retrieveride'),
    url(r'^retrieveride/', views.retrieveride.as_view(), name='retrieveride'),
    url(r'^retrieverequiredrides/', views.retrieverequiredrides, name='retrieverequiredrides'),
    url(r'^makerequestride/', views.makerequestride, name='makerequestride'),
    url(r'^sendinvitetopool/', views.sendinvitetopool, name='sendinvitetopool'),
    url(r'^makerequestride/', views.makerequestride, name='makerequestride'),
]

carpool/routes/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Route(models.Model):
	lats = models.TextField()
	longs = models.TextField()
	timereq = models.IntegerField()
	startlat = models.DecimalField(max_digits=15, decimal_places=12)
	endlat = models.DecimalField(max_digits=15, decimal_places=12)
	startlong = models.DecimalField(max_digits=15, decimal_places=12)
	endlong = models.DecimalField(max_digits=15, decimal_places=12)
	minlat = models.DecimalField(max_digits=15, decimal_places=12)
	maxlat = models.DecimalField(max_digits=15, decimal_places=12)
	minlong = models.DecimalField(max_digits=15, decimal_places=12)
	maxlong = models.DecimalField(max_digits=15, decimal_places=12)

class Pools(models.Model):
	time = models.TimeField()
	date = models.DateField()
	route = models.ForeignKey(Route)
	route_reverse = models.BooleanField()
	user = models.ForeignKey(User)

class Riderequest(models.Model):
	time = models.TimeField()
	date = models.DateField()
	startlat = models.DecimalField(max_digits=15, decimal_places=12)
	endlat = models.DecimalField(max_digits=15, decimal_places=12)
	startlong = models.DecimalField(max_digits=15, decimal_places=12)
	endlong = models.DecimalField(max_digits=15, decimal_places=12)
	user = models.ForeignKey(User)
	accepted = models.BooleanField()

class Invites(models.Model):
	pool = models.ForeignKey(Pools)
	hashstring = models.CharField(max_length=255)
	riderequest = models.ForeignKey(Riderequest)
	is_from_driver = models.BooleanField()

carpool/routes/admin.py
from django.contrib import admin
from .models import Pools, Route

# Register your models here.

admin.site.register(Pools)
admin.site.register(Route)

carpool/routes/tests.py
from django.test import TestCase

# Create your tests here.

carpool/routes/views.py
''' THE CONTROLLER FOR THE POOLS AND ROUTES '''
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.template import RequestContext, loader, Context
from django.core.urlresolvers import reverse
from django.views.generic import View
from django.core.cache import cache
from .models import Pools, Route, Riderequest, Invites
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator	
from django.views.decorators.csrf import ensure_csrf_cookie
from django.core.mail import send_mail, BadHeaderError
import socket
import hashlib
import datetime




##################################################################################################################################################################
################################### THE APP CONTROLS ALL OF THE FUNCTIONS THAT DEAL WITH THE CRUD OF THE USER POOLS AND RIDES ####################################
##################################################################################################################################################################



#the global variable for storing the lat longs if the user chooses to refresh the page...
#the global variable for checking if the user has requested that ride or not ( used in checking invitation )

#the function for displaying the initial page for posting a carpool
@login_required
def postride(request):
	return render(request, 'routes/postride.html')

class createride(View):

	def retrievedata(self, request):
		startlat = float(request.POST.get("startlat", ""))
		startlong = float(request.POST.get("startlong", ""))
		endlat = float(request.POST.get("endlat", ""))
		endlong = float(request.POST.get("endlong", ""))
		minlat = float(request.POST.get("minlat", ""))
		maxlat = float(request.POST.get("maxlat", ""))
		minlong = float(request.POST.get("minlong", ""))
		maxlong = float(request.POST.get("maxlong", ""))
		timereq = int(request.POST.get("timereq", ""))
		latstr = request.POST.get("latstr", "")
		latstr = latstr[1:]
		longstr = request.POST.get("longstr", "")
		longstr = longstr[1:]
		dates = request.POST.get("date", "")
		dates = dates.split(", ")
		time = request.POST.get("time", "")
		time = datetime.datetime.strptime(time, '%H:%M').time()
		user = request.user
		data = {'startlat': startlat, 'startlong': startlong, 'endlat': endlat, 'endlong': endlong, 'minlat': minlat, 'minlong': minlong, 'timereq': timereq, 'latstr': latstr, 'longstr': longstr, 'dates': dates, 'time': time, 'user': user}
		return data

	@method_decorator(login_required)
	def post(self, request, *args, **kwargs):
		#retrieve the data collected from post variables
		data = self.retrievedata(request)
		#check if there exists a route already to the route that has to be inserted
		try:
			p = Route.objects.get(endlat__range = (data['endlat'] - 0.0000000001, data['endlat'] + 0.0000000001), startlat__range = (data['startlat'] - 0.0000000001, data['startlat'] + 0.0000000001), endlong__range = (data['endlong'] - 0.0000000001, data['endlong'] + 0.0000000001), startlong__range = (data['startlong'] - 0.0000000001, data['startlong'] + 0.0000000001))
			#on success assign the route to the route object recieved
			route = p
			route_reverse = False
		except Route.DoesNotExist:
			try:
				#check if the route exists in reverse order
				#eg if your route is A->B, check if B->A exists
				p = Route.objects.get(startlat__range = (data['endlat'] - 0.0000000001, data['endlat'] + 0.0000000001), endlat__range = (data['startlat'] - 0.0000000001, data['startlat'] + 0.0000000001), startlong__range = (data['endlong'] - 0.0000000001, data['endlong'] + 0.0000000001), endlong__range = (data['startlong'] - 0.0000000001, data['startlong'] + 0.0000000001))
				route = p
				#mark the route as reversed
				route_reverse = True
			except Route.DoesNotExist:
				#if the route does not exist either in reversed or non reversed form, create the route
				p = Route(lats = data['latstr'], longs = data['longstr'], startlat = data['startlat'], endlat = data['endlat'], startlong = data['startlong'], endlong = data['endlong'], minlat = data['minlat'], maxlat = data['maxlat'], minlong = data['minlong'], maxlong = data['maxlong'], timereq = data['timereq'])
				p.save()
				routeid = p
				route_reverse = False
		for date in data['dates']:
			#for each of the date, create a carpool..
			datereq = date[:6] + date[8:]
			datereq = datetime.datetime.strptime(datereq, '%m/%d/%y').date()
			q = Pools(time = data['time'], date = datereq, route = p, user = data['user'], route_reverse = route_reverse)
			q.save()
		return HttpResponse(type(data['startlat']))


#the function for displaying the initial page for searching a carpool
@login_required
def getride(request):
	return render(request, 'routes/getride.html')

@login_required
def makerequestride(request):
	request.session['riderequest'] = True
	#riderequest = True
	return HttpResponse(request.session['riderequest'])

#this function displays the data through ajax .load function in pagenation
@login_required
@ensure_csrf_cookie
def retrieverequiredrides(request):
	#get the page id that has been requested
	page_id = int(request.GET.get("page", ""))
	print page_id
	ridereq = cache.get('recentridesearched')
	#get the required results only.. for now 3 per page..
	cache.get(ridereq)[(page_id - 1)*3:(page_id - 1)*3 + 3]
	context = {'results': cache.get(ridereq)[(page_id - 1)*3:(page_id - 1)*3 + 3], 'requestride': request.session['riderequest']}
	return render(request, 'routes/displayrequiredroutes.html', context)

#the function manages the requests that are sent to the users to join carpools ( either way )
#class managerequest(View):
#	def post(self, request, *args, **kwargs):

@login_required
def sendinvitetopool(request):
	poolid = int(request.GET.get("poolid", ""))
	pool = Pools.objects.get(id=poolid)
	pooluser = pool.user
	subject = "Pool Joining Request By " + request.user.first_name + " " + request.user.last_name
	message = "Hi " + pooluser.first_name + "\n" + request.user.first_name + " " + request.user.last_name + " has sent you a request to join your carpool..."
	send_mail(subject, message, "contact@spa.com", [pooluser.email])
	return HttpResponse("success")

class retrieveride(View):

	def getip(self, request):
		return [(s.connect(('8.8.8.8', 80)), s.getsockname()[0], s.close()) for s in [socket.socket(socket.AF_INET, socket.SOCK_DGRAM)]][0][1]

	def retrievedata(self, request):
		#handling the global variables for refresh conditions
		#these specify the lat longs of the user ( for the purpose of drawing the users route on the map)
		latlongs = []
		latlongs.append(float(request.POST.get("startlat", "")))
		latlongs.append(float(request.POST.get("startlong", "")))
		latlongs.append(float(request.POST.get("endlat", "")))
		latlongs.append(float(request.POST.get("endlong", "")))
		print latlongs
		request.session['latlongs'] = latlongs
		dates = request.POST.get("date", "")
		dates = dates.split(", ")
		time = request.POST.get("time", "")
		time = datetime.datetime.strptime(time, '%H:%M').time()
		for date in dates:
			datereq = date[:6] + date[8:]
			datereq = datetime.datetime.strptime(datereq, '%m/%d/%y').date()
		data = {'startlat': float(request.POST.get("startlat", "")), 'startlong': float(request.POST.get("startlong", "")), 'endlat': float(request.POST.get("endlat", "")), 'endlong': float(request.POST.get("endlong", "")), 'km': float(request.POST.get("km", "")), 'datereq': datereq, 'time': time}
		return data

	def filteronroute(self,request,data,q2):
		routes = []
		routeids = []
		startmatchlist = []
		endmatchlist = []
		for objects in q2:
			lats = objects.lats
			longs = objects.longs
			lats = lats.split(",")
			longs = longs.split(",")
			latsf = [float(i) for i in lats]
			longsf = [float(i) for i in longs]
			longmatchstart1 = [ n for n,i in enumerate(longsf) if i>data['startlong'] - (0.005*data['km']) ]
			longmatchstart2 = [ n for n,i in enumerate(longsf) if i<data['startlong'] + (0.005*data['km']) ]
			latmatchstart1 = [ n for n,i in enumerate(latsf) if i>data['startlat'] - (0.005*data['km']) ]
			latmatchstart2 = [ n for n,i in enumerate(latsf) if i<data['startlat'] + (0.005*data['km']) ]
			startmatch = set(longmatchstart1)&set(longmatchstart2)&set(latmatchstart1)&set(latmatchstart2)
			startmatch = list(startmatch)
			longmatchend1 = [ n for n,i in enumerate(longsf) if i>data['endlong'] - (0.005*data['km']) ]
			longmatchend2 = [ n for n,i in enumerate(longsf) if i<data['endlong'] + (0.005*data['km']) ]
			latmatchend1 = [ n for n,i in enumerate(latsf) if i>data['endlat'] - (0.005*data['km']) ]
			latmatchend2 = [ n for n,i in enumerate(latsf) if i<data['endlat'] + (0.005*data['km']) ]
			endmatch = set(longmatchend1)&set(longmatchend2)&set(latmatchend1)&set(latmatchend2)
			endmatch = list(endmatch)
			#on suceesful match, append the route to the lists
			if(len(startmatch) and len(endmatch)):
				routes.append(objects)
				routeids.append(objects.id)
				startmatchlist.append(startmatch)
				endmatchlist.append(endmatch)
		returndata =  {'routes': routes, 'routeids': routeids, 'startmatchlist': startmatchlist, 'endmatchlist': endmatchlist}		
		return returndata

	@method_decorator(login_required)
	def get(self, request, *args, **kwargs):
		ridereq = cache.get('recentridesearched')
		print ridereq
		if len(cache.get(ridereq)) % 3 == 0:
			pages = len(cache.get(ridereq))/3
		else:
			pages = len(cache.get(ridereq))/3 + 1
		context = {'results': cache.get(ridereq)[0:3], 'pagerange': [x+1 for x in range(0,pages)], 'current': 0, 'userdata': request.session['latlongs'], 'requestride': request.session['riderequest']}
		return render(request, 'routes/showrides.html', context)

	@method_decorator(login_required)
	def post(self, request, *args, **kwargs):
		request.session['riderequest'] = False

carpool/carpool/templates/routes/displayrequiredroutes.html
{% for objects in results %}
<div id="{{ objects.id }}" style="width:700px; height:70px; border: 2px solid #000;" onmouseover="showroute(this.id)" onmouseout="hideroute(this.id)" class="normalride">
Ride posted by {{ objects.user.first_name }}
<br>
Ride starts at {{ objects.date }} at {{ objects.time }} and would be {{ objects.route.timereq }} minutes long
<input type="hidden" value="{{ objects.route.startlat }}" id="{{ objects.id }}startlat" />
<input type="hidden" value="{{ objects.route.startlong }}" id="{{ objects.id }}startlong" />
<input type="hidden" value="{{ objects.route.endlat }}" id="{{ objects.id }}endlat" />
<input type="hidden" value="{{ objects.route.endlong }}" id="{{ objects.id }}endlong" />
{% if requestride == True %}
<button type="button" onclick="sendrequest(this.id)" id="request{{ objects.id }}">Send him a request</button>
{% endif %}
</div>
</div>
<br>
{% endfor %}

carpool/carpool/templates/routes/getride.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places"></script>
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
	<script src="{% static "routes/js/jquery-ui.min.js" %}"></script>
	<script src="{% static "routes/js/jquery-ui.multidatespicker.js" %}"></script>
	<script src="{% static "routes/js/jquery.ui.timepicker.js" %}"></script>
	<script src="{% static "routes/js/google_location_bar.js" %}"></script>
	<script src="{% static "routes/js/datetimepicker_script.js" %}"></script>
	<link rel="stylesheet" href="{% static "routes/css/jquery-ui.min.css" %}">
	<link rel="stylesheet" href="{% static "routes/css/jquery-ui.theme.min.css" %}">
	<link rel="stylesheet" href="{% static "routes/css/jquery.ui.timepicker.css" %}">
</head>
<body>
	<input id="start" class="form-control" placeholder="Start Point" type="text" style="float: left;width: 60%;">
	<br>
	<input id="end" class="form-control" placeholder="End Point" type="text" style="float: left;width: 60%;">
	<br>
	<form action="{% url 'routes:retrieveride' %}" method="post">
	{% csrf_token %}
	<input type="hidden" id="startlat" name="startlat"/>
	<input type="hidden" id="startlong" name="startlong"/>
	<input type="hidden" id="endlat" name="endlat"/>
	<input type="hidden" id="endlong" name="endlong"/>
	<br>
	<input id="datepicker" placeholder="Select Dates" name="date"/>
	<br>
	<input id="timepicker" placeholder="Select Time" name="time"/>
    <br>
    Please let us know how much can you manage by yourself:
	<select name="km">
		<option value="1">1 Km</option>
		<option value="2">2 Km</option>
		<option value="3">3 Km</option>
		<option value="4">4 Km</option>
		<option value="5">5 Km</option>
		<option value="6">6 Km</option>
		<option value="7">7 Km</option>
		<option value="8">8 Km</option>
		<option value="9">9 Km</option>
		<option value="10">10 Km</option>
	</select>
	<br>
	<input type="submit" value="Find me Rides" />
</body>
</html>

carpool/carpool/templates/routes/showrides.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places"></script>
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
	<script src="{% static "routes/js/jquery-ui.min.js" %}"></script>
	<script src="{% static "routes/js/jquery-ui.multidatespicker.js" %}"></script>
	<script src="{% static "routes/js/jquery.ui.timepicker.js" %}"></script>
	<script src="{% static "routes/js/google_location_bar1.js" %}"></script>
	<script src="{% static "routes/js/datetimepicker_script.js" %}"></script>
	<link rel="stylesheet" href="{% static "routes/css/jquery-ui.min.css" %}">
	<link rel="stylesheet" href="{% static "routes/css/jquery-ui.theme.min.css" %}">
	<link rel="stylesheet" href="{% static "routes/css/jquery.ui.timepicker.css" %}">
	<style>
		.selected{
			background-color: orange;
		}
	</style>
	<script>
		var map;
		var tempmarkers = [];
		var temppoly = "";
		function showinitialmap(){
			markers = [
	            {
	                "title": 'Start Point',
	                "lat": '{{ userdata.0 }}',
	                "lng": '{{ userdata.1 }}'
	            }
	        ,
	            {
	                "title": 'End Point',
	                "lat": '{{ userdata.2 }}',
	                "lng": '{{ userdata.3 }}'
	            }
    		];
    		var mapOptions = {
	            center: new google.maps.LatLng(markers[0].lat, markers[0].lng),
	            zoom: 10,
	            mapTypeId: google.maps.MapTypeId.ROADMAP
	        };
	        map = new google.maps.Map(document.getElementById("map_canvas"), mapOptions);
	        var infoWindow = new google.maps.InfoWindow();
	        var lat_lng = new Array();
	        var latlngbounds = new google.maps.LatLngBounds();
	        for (i = 0; i < markers.length; i++) {
	            var data = markers[i]
	            var myLatlng = new google.maps.LatLng(data.lat, data.lng);
	            lat_lng.push(myLatlng);
	            var marker = new google.maps.Marker({
	                position: myLatlng,
	                map: map,
	                title: data.title
	            });
	            latlngbounds.extend(marker.position);
	            (function (marker, data) {
	                google.maps.event.addListener(marker, "click", function (e) {
	                    infoWindow.setContent(data.description);
	                    infoWindow.open(map, marker);
	                });
	            })(marker, data);
	        }
	        map.setCenter(latlngbounds.getCenter());
	        map.fitBounds(latlngbounds);

	        //***********ROUTING****************//
 
	        //Initialize the Path Array
	        var path = new google.maps.MVCArray();
	        //Initialize the Direction Service
	        var service = new google.maps.DirectionsService();
	        //Set the Path Stroke Color
	        var poly = new google.maps.Polyline({ map: map, strokeColor: '#4986E7' });
	        //Loop and Draw Path Route between the Points on MAP
	        for (var i = 0; i < lat_lng.length; i++) {
	            if ((i + 1) < lat_lng.length) {
	                var src = lat_lng[i];
	                var des = lat_lng[i + 1];
	                path.push(src);
	                poly.setPath(path);
	                service.route({
	                    origin: src,
	                    destination: des,
	                    travelMode: google.maps.DirectionsTravelMode.DRIVING
	                }, function (result, status) {
	                    if (status == google.maps.DirectionsStatus.OK) {
	                        for (var i = 0, len = result.routes[0].overview_path.length; i < len; i++) {
	                            path.push(result.routes[0].overview_path[i]);
	                        }
	                    }
	                });
	            }
	        }
		}
		function showroute(id){
			tempmarkers = [];
			temppoly = "";
			var hovered = '#' + id;
			$(hovered).addClass('selected');
			var markers1 = [
	            {
	                "title": 'Start Point',
	                "lat": document.getElementById(id + "startlat").value,
	                "lng": document.getElementById(id + "startlong").value
	            }
	        ,
	            {
	                "title": 'End Point',
	                "lat": document.getElementById(id + "endlat").value,
	                "lng": document.getElementById(id + "endlong").value
	            }
    		];
    		var markericon = "{% static "routes/css/images/marker.png" %}";
    		var infoWindow = new google.maps.InfoWindow();
	        var lat_lng = new Array();
	        var latlngbounds = new google.maps.LatLngBounds();
	        for (i = 0; i < markers1.length; i++) {
	            var data = markers1[i]
	            var myLatlng = new google.maps.LatLng(data.lat, data.lng);
	            lat_lng.push(myLatlng);
	            var marker = new google.maps.Marker({
	                position: myLatlng,
	                map: map,
	                title: data.title,
	                icon: markericon
	            });
	            latlngbounds.extend(marker.position);
	            (function (marker, data) {
	                google.maps.event.addListener(marker, "click", function (e) {
	                    infoWindow.setContent(data.description);
	                    infoWindow.open(map, marker);
	                });
	            })(marker, data);
	            tempmarkers.push(marker);
	        }
	        //***********ROUTING****************//
 
	        //Initialize the Path Array
	        var path = new google.maps.MVCArray();
	        //Initialize the Direction Service
	        var service = new google.maps.DirectionsService();
	        //Set the Path Stroke Color
	        temppoly = new google.maps.Polyline({ map: map, strokeColor: '#DA70D6' });
	        //Loop and Draw Path Route between the Points on MAP
	        for (var i = 0; i < lat_lng.length; i++) {
	            if ((i + 1) < lat_lng.length) {
	                var src = lat_lng[i];
	                var des = lat_lng[i + 1];
	                path.push(src);
	                temppoly.setPath(path);
	                service.route({
	                    origin: src,
	                    destination: des,
	                    travelMode: google.maps.DirectionsTravelMode.DRIVING
	                }, function (result, status) {
	                    if (status == google.maps.DirectionsStatus.OK) {
	                        for (var i = 0, len = result.routes[0].overview_path.length; i < len; i++) {
	                            path.push(result.routes[0].overview_path[i]);
	                        }
	                    }
	                });
	            }
	        }
		}
		function getpage(pageid){
			alert("i'm called");
			urlreq = "{% url 'routes:retrieverequiredrides' %}" + "?page=" + pageid;
			$("#container").load(urlreq);
		}
		function hideroute(id){
			var hovered = '#' + id;
			$(hovered).removeClass('selected');
			for(var i=0; i < tempmarkers.length; i++){
				tempmarkers[i].setMap(null);
			}
			temppoly.setMap(null);
			console.log(id);
		}
		function sendrequest(id){
			userid = id.substr(7);
			urlreq = "{% url 'routes:sendinvitetopool' %}" + "?poolid=" + userid;
			alert("called");
			$.ajax({
				url: urlreq
			})
			.done(function(msg){
				alert("Your mail has been sent")
			});
		}
		function requestride(){
			$.ajax({
				url: "{% url 'routes:makerequestride' %}"
			})
			.done(function(msg){
				alert("hi")
				urlreq = "{% url 'routes:retrieverequiredrides' %}" + "?page=1";
				$("#container").load(urlreq);
			});
		}
		window.onload = showinitialmap;
	</script>
</head>
<body>
<div id="map_canvas" style="width:700px; height:500px; border: 5px solid #000;"></div>
<div id="container">
{% for objects in results %}
<div id="{{ objects.id }}" style="width:700px; height:70px; border: 2px solid #000;" onmouseover="showroute(this.id)" onmouseout="hideroute(this.id)" class="normalride">
Ride posted by {{ objects.user.first_name }}
<br>
Ride starts at {{ objects.date }} at {{ objects.time }} and would be {{ objects.route.timereq }} minutes long
<input type="hidden" value="{{ objects.route.startlat }}" id="{{ objects.id }}startlat" />
<input type="hidden" value="{{ objects.route.startlong }}" id="{{ objects.id }}startlong" />
<input type="hidden" value="{{ objects.route.endlat }}" id="{{ objects.id }}endlat" />
<input type="hidden" value="{{ objects.route.endlong }}" id="{{ objects.id }}endlong" />
{% if requestride == True %}
<button type="button" onclick="sendrequest(this.id)" id="request{{ objects.id }}">Send him a request</button>
{% endif %}
</div>
<br>
{% endfor %}
</div>
{% for i in pagerange %}
<a onclick="getpage('{{ i }}')">{{ i }}</a>
{% endfor %}
<button onclick="requestride()" type="button">Request a ride</button>
</body>
</html>